name: DAST
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    name: ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Bulding container
        run: docker build -t my-apache2 .

      - name: run docker
        run: docker run -d -p 80:80 --name docker-apache -d my-apache2

      - name: delete index html
        run: docker exec docker-apache rm -rf /usr/local/apache2/htdocs/index.html

      - name: check conf server
        run: docker exec docker-apache ll /usr/local/apache2

      - name: check server
        run: curl http://localhost:80

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:80'
      
      - name: stop docker
        run: docker stop docker-apache
     
